CREATE TABLE IF NOT EXISTS players (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    active INTEGER NOT NULL DEFAULT 1,
    team TEXT NOT NULL DEFAULT 'Challenger',
    gender TEXT NOT NULL DEFAULT 'Unspecified'
);

CREATE TABLE IF NOT EXISTS schedule_windows (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    submission_open INTEGER NOT NULL DEFAULT 1,
    public_token TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS practice_slots (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_window_id INTEGER NOT NULL REFERENCES schedule_windows(id),
    date TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    location TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS locations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS availability (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id INTEGER NOT NULL REFERENCES players(id),
    practice_slot_id INTEGER NOT NULL REFERENCES practice_slots(id),
    available INTEGER NOT NULL DEFAULT 1,
    updated_at TEXT NOT NULL,
    UNIQUE(player_id, practice_slot_id)
);

CREATE TABLE IF NOT EXISTS assignments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    practice_slot_id INTEGER NOT NULL REFERENCES practice_slots(id),
    player_id INTEGER NOT NULL REFERENCES players(id),
    is_practice_lead INTEGER NOT NULL DEFAULT 0,
    UNIQUE(practice_slot_id, player_id)
);

-- INSERT INTO players (name, active, team, gender)
-- VALUES
--     ('Isaac', 1, 'Challenger', 'Unspecified'),
--     ('Eli', 1, 'Challenger', 'Unspecified'),
--     ('Benjamin', 1, 'Challenger', 'Unspecified'),
--     ('Tyler', 1, 'Challenger', 'Unspecified')
-- ON CONFLICT(name) DO NOTHING;
